n1=int(input ("enter the first number"))
n2=int(input("enter the second number"))
x=n1
y=n2
while(n2!=0):
    t=n2
    n2=n1%n2
    n1=t
gcd=n1
print ("gcd=",gcd)
lcm=x*y/gcd
print("lcm=",lcm)